
# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - CGO_ENABLED=0
  - GOFLAGS=-mod=vendor
  - GO111MODULE=auto

builds:
  - id: helmplate
    binary: helmplate
    main: ./cmd/helmplate
    goos:
      # - freebsd
#      - windows
      - darwin
#      - linux
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=mod